name: sourcetoad/aws-ecs-deploy-action
on: push

permissions:
  contents: read

jobs:
  bash-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Lint Bash
        uses: azohra/shell-linter@6bbeaa868df09c34ddc008e6030cfe89c03394a1 # latest
        with:
          path: '*.sh'
